### ISSUE TITLE
Wrong speaker used

### ISSUE THREAD

**Issue by sdac** [Temasys/SkylinkSDK-iOS-Sample#1]
On an iPhone 5s, the incoming audio is played back using the wrong speaker (as if the device was held up during a phone call). Setting the audio session category to AVAudioSessionCategoryPlayAndRecord causes this on some devices. The workaround is to use AVAudioSession's overrideOutputAudioPort (AVAudioSessionPortOverride.Speaker). This probably needs to be done inside the SDK itself (actualy every time the audio session category is changed) and preferably exposed as an API to control the behaviour.

**Comment by janiduw** [comment]
@sdac I made a change to the sample application to change the audio routing. I tested on a iPhone 5s and now the audio starts with the speaker phone. We will try to keep the audio routing on the application side as the SDK might be used in different use cases and we would want the users to handle the audio as they like it. This is similar to the behaviour of the Web-RTC native library and its sample application.
