### ISSUE TITLE
Rotation lock

### ISSUE THREAD

**Issue by danlniel** [Temasys/SkylinkSDK-iOS-Sample#10]
Is there any way to lock rotation created by the camera?
I try to lock the app rotation but for camera itself doesnt work
Thanks.

**Comment by RomainPln** [comment]
Hello Daniel.
Technically, the size of the captured video changes ([w,h] becomes [h,w]), not it's orientation (even if this size is directly related to device orientation). You can observe the same behavior in Apple's Camera app even with rotation lock enabled.
What I could suggest for example is play with the rendered view to make it appear as you wish, for example apply a 90 degrees rotation.
