### ISSUE TITLE
How to set UserInfo for every connection

### ISSUE THREAD

**Issue by axer0310** [Temasys/SkylinkSDK-iOS-Sample#11]
As title

I tried to use sendUser to update a connection and getUserInfo to print out the userInfo I just send, but all I get is nil, can somebody help?

my code is like this:

        var config = SKYLINKConnectionConfig()
        config.audio = true;
        config.video = true;
        var chat : SKYLINKConnection?
        chat = SKYLINKConnection.init(config: config, appKey: MYAPPKEY)
        
        chat?.lifeCycleDelegate = self
        chat?.mediaDelegate = self
        chat?.remotePeerDelegate = self

        SKYLINKConnection.setVerbose(true)
        var dic: NSDictionary = ["NickName": "123456"]
        chat?.connectToRoom(withSecret: "iv4gws9a0l1h5", roomName: "123", userInfo: dic)

and I set up a button, which after pressed will execute following

        chat?.sendUserInfo(dic)
        if let id = chat?.myPeerId
        {
             let user = chat!.getUserInfo(id) as? NSDictionary
             print("userInfo: \(user)")
        }

when I tried to print user, it's always nil

**Comment by RomainPln** [comment]
Hello. What is the value of dic when the button is pressed? 
If you remove the following line from the IBAction, do you get a value for user ? 
`chat?.sendUserInfo(dic)`
(given that a value is set at connection time, you should).

**Comment by axer0310** [comment]
Unfortunately it still not showing.
Does it has anything to do whether my chat is connected to server?
Cuz I set SKYLINKConnection to verbose, and in my console after I connect to server, it shows the following

> <INFO> SkylinkSDK for iOS v_1.0.10
2017-03-24 11:28:46.033 ****[4079:7901950]  ⚠️ <WARNING>  ► Local video capturing is not supported on Simulator
2017-03-24 11:28:46.240 ****[4079:7901950] <INFO> Processing the room server response ...
2017-03-24 11:28:46.241 ****[4079:7901950] <INFO> Connecting to the room...
2017-03-24 11:28:46.242 ****[4079:7901950] <INFO> Successfully processed room info from App server
2017-03-24 11:28:46.521 ****[4079:7901950] SocketRocket: In debug mode.  Allowing connection to any root cert
2017-03-24 11:28:47.061 deKKo[4079:7901950] <INFO> [Handshake] Processing inRoom


And by saying every connection I mean every SKYLINKConnection.
Cuz users should use different SKYLINKConnection instances to connect to server, and we want to give them different userInfo based on their userName.

**Comment by axer0310** [comment]
and the dic inside 

    chat?.sendUserInfo(dic)

is the same as I declare as above

**Comment by RomainPln** [comment]
Does this happen on real device (instead of simulator) ?
