### ISSUE TITLE
Is it still work version???

### ISSUE THREAD

**Issue by fix2015** [Temasys/SkylinkSDK-iOS-Sample#12]
Hi everybody, i try run this example, did everything that you wrote in README, but it doesn't run, it give error "Invalid argument" and lot of error. Can you check?
<img width="934" alt="2017-05-31 11 57 48" src="https://cloud.githubusercontent.com/assets/3988392/26624126/98890a16-45f8-11e7-8016-ae8aeff4ecad.png">

**Comment by fix2015** [comment]
i tried Swift version had Build Failed
<img width="1073" alt="2017-05-31 13 10 47" src="https://cloud.githubusercontent.com/assets/3988392/26627316/ba282954-4602-11e7-9671-209ecfb3f9f8.png">

**Comment by fix2015** [comment]
tried on 2 laptop same result, @RomainPln did you notice that?

**Comment by amanak2** [comment]
facing exactly same issue. Xcode8 just fills up with errors

**Comment by RomainPln** [comment]
Hello. This seems related to swift syntax update in swift 3.
Have you tried setting the project as swift 2 ?
Note that this is just a sample app meant to illustrate the usage of Skylink SDK, the purpose is to give example to make it easier to get the concepts before writing your own app. This app was written last year, we decided to leave it on github after swift update tho in case it helps.

**Comment by amanak2** [comment]
my main issue was that the dependencies like SocketRocket you are using need to be updated

**Comment by RomainPln** [comment]
Oh in that case, doesn't running pod update do the trick ?

**Comment by amanak2** [comment]
No it still uses the same old version of dependencies even after running pod update. I guess it gets the version Skylink pod is using at the time

**Comment by RomainPln** [comment]
Does your podfile contains pod "SKYLINK" or some specific branch/tag ? tried the usual clean/empty derived data ?

**Comment by amanak2** [comment]
just pod 'SKYLINK'

**Comment by RomainPln** [comment]
@lyx501135 Has this been fixed?

**Comment by lyx501135** [comment]
Yes, fixed
