### ISSUE TITLE
Working with Firebase

### ISSUE THREAD

**Issue by Hamza123Imran** [Temasys/SkylinkSDK-iOS-Sample#14]
I developing chat app, i want to confirm that will this will work with firebase? because my app backend is in firebase and i want video and audio call in the app.

**Comment by RomainPln** [comment]
Hello, yes, Skylink SDK's video and audio call will work in an app that uses Firebase for it's backend. Therefore I'm closing this but feel free to re-open if you happen to notice any issue.

**Comment by Hamza123Imran** [comment]
Can u provide any link for that or tutorials that how can integrate this with my firebase backend?

**Comment by RomainPln** [comment]
No as of now the SDK is written in Objective-C but it works in swift implementations like any other ObjC SDK, you can refer to this thread https://github.com/Temasys/SkylinkSDK-iOS-Sample/issues/15
