### ISSUE TITLE
Swift version of skylink

### ISSUE THREAD

**Issue by Hamza123Imran** [Temasys/SkylinkSDK-iOS-Sample#15]
How i can get the swift version of skylink?

**Comment by Hamza123Imran** [comment]
How to implement this in swift

**Comment by RomainPln** [comment]
By simply using the Swift syntax after installing via cocoapods.

**Comment by Hamza123Imran** [comment]
pods will remain same?

**Comment by RomainPln** [comment]
Not sure to understand the question here. Please refer to [this comment](https://github.com/Temasys/SkylinkSDK-iOS-Sample/issues/15#issuecomment-412418943).

**Comment by Hamza123Imran** [comment]
I'm asking that if i install through pods it will install the objective c class in my project than how will i import the lib?

**Comment by lyx501135** [comment]
The Swift version is here https://github.com/Temasys/SkylinkSDK_iOS_SampleApp_Swift4, for both Xcode 9 and 10

**Comment by lyx501135** [comment]
Just ‘pod install’ in the Podfile folder

**Comment by lyx501135** [comment]
My pleasure friend, if you want to try the test version(usually the pre-release version), you may modify the Podfile before running the pod install 
pod 'SKYLINK', :git => 'https://github.com/Temasys/SKYLINK-iOS.git', :branch => 'test'
