### ISSUE TITLE
Cannot assign to 'isRemote' in 'videoView' issue running in the simulator with SampleAppSwift 

### ISSUE THREAD

**Issue by swells808** [Temasys/SkylinkSDK-iOS-Sample#3]
Running in the simulator and after compile the error pops up. Any ideas?

**Comment by sumairasaeed** [comment]
I commented that line. And it built successfully

**Comment by sumairasaeed** [comment]
I think we can replace it with this:
videoView.setRemote(false)

**Comment by RomainPln** [comment]
This is closed as it was related to an old version of the sample app.
