### ISSUE TITLE
ld: library not found for -lObjC

### ISSUE THREAD

**Issue by ashishuniyal3** [Temasys/SkylinkSDK-iOS-Sample#5]
I tried on one of my mac mini but got this error. And then I tried on other systems the application ran fine. Can you please tell me what could be reason. I tried to search the library because of which the error is displayed. So let me know.

**Comment by RomainPln** [comment]
Hello, thank you for reporting.
What OS X and Xcode version are you using ? 
If you have a flag name -l"ObjC" in other linker flags (build settings) you can try removing it (keep -ObjC tho).

**Comment by ashishuniyal3** [comment]
The OSX version is El Capitain 10.11 and the xcode version is 7.1. I removed the linker flags but even though it showed same error.

**Comment by wilonth** [comment]
Same issue on Xcode 8.1, why is this closed?

**Comment by RomainPln** [comment]
Try replacing other linker flags with with $(inherited) then and check if -ObjC is automatically included.
