### ISSUE TITLE
Unsupported URL with Sample app

### ISSUE THREAD

**Issue by rwh23** [Temasys/SkylinkSDK-iOS-Sample#6]
Hello, 
While I run sample app with my App ID an secret key, I have Connection failed with "While connecting to the room server: error.code -> -1002, error.description -> Unsupported URL"
Can anyone help me in this position? 
Thanks

**Comment by RomainPln** [comment]
Hello, 
Given the error message, it seems you are using the wrong credentials. 
You can find both of it in the developer console (http://developer.temasys.com.sg) on the app key details, respectively under 'ID' and 'secret'. If that is what you've done or if you have trouble finding it, please drop us a support note here: http://support.temasys.com.sg/support/tickets/new and we will be reaching out to you shortly.
