### ISSUE TITLE
Sample App Crashes on iOS 10

### ISSUE THREAD

**Issue by odrobnik** [Temasys/SkylinkSDK-iOS-Sample#7]
When launching the sample app under iOS 10 it crashes with the following message given on the console:

```
This app has crashed because it attempted to access privacy-sensitive data 
without a usage description.  The app's Info.plist must contain an
 NSCameraUsageDescription key with a string value explaining to the user 
how the app uses this data.
```

**Comment by RomainPln** [comment]
Thank you for raising this issue, we are aware of this and it should be fixed in next release. By the meantime, can you confirm adding the NSCameraUsageDescription to your info.plist solves the issue ?

**Comment by odrobnik** [comment]
Yes, the app runs if I add the missing key.

**Comment by RomainPln** [comment]
Updates adds iOS10+ required key in info.plist
