### ISSUE TITLE
1-1 Video Call doesn't work, but Multi-Party Does

### ISSUE THREAD

**Issue by odrobnik** [Temasys/SkylinkSDK-iOS-Sample#8]
What reason could there be that the 1-1 Video Call does not get peer video, but with the same credentials the Multi-Party VC shows video?

I cannot see any difference in the setup of the view controller.

To clarify: I am on iOS 10 and I have specified the correct api key and secret. I changed the room name to another one. I did the same in both `VideoCallViewController` as well as `MuliVideoCallViewController`. If I go into the former, then I only see my own video. If I go into the latter, I see peer video. 

Is that a bug in the sample app? Or what are you doing differently in the multi video call controller so that the remote video works?

**Comment by RomainPln** [comment]
Hello, this is weird, please double check the peer you expect to see in the 1-1 video VC is connected to the same room name (and key). Have you changed anything to the code?

**Comment by RomainPln** [comment]
Should be OK, please let us know if you ever experience the issue.
